/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs.Registration

import uk.gov.hmrc.ui.pages.*
import uk.gov.hmrc.ui.specs.BaseSpec

class CheckYourAnswersSpec extends BaseSpec {

  private val registration = Registration
  private val auth         = Auth
  private val email        = EmailVerification

  Feature("Check your answers") {

    Scenario("Changing answers in Check Your Answers") {

      Given("the user accesses the OSS Registration Service")
      auth.goToAuthorityWizard()
      auth.loginUsingAuthorityWizard("100000001", "Organisation", "vatOnly", "registration")
      registration.checkJourneyUrl("already-eu-registered")

      When("the user adds answers to their registration")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("sell-from-northern-ireland")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("northern-ireland-business")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("business-pay")
      registration.continue()
      registration.checkJourneyUrl("confirm-vat-details")
      registration.answerVatDetailsChoice("Yes")
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("already-made-sales")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("date-of-first-sale")
      registration.enterDate("yesterday")
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/1")
      registration.selectCountry("Latvia")
      registration.checkJourneyUrl("previous-scheme/1/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/1/1")
      registration.enterAnswer("LV01234567899")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("start-date")
      registration.continue()
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("online-marketplace")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("give-website-address")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("business-contact-details")
      registration.fillContactDetails("Joe Bloggs", "01234567890", "email@test.com")
      email.completeEmailVerification("registration")
      registration.checkJourneyUrl("bank-details")
      registration.fillBankAccountDetails("Account Name", "SMCOGB2LXXM", "GB29NWBK60161331926819")
      registration.checkJourneyUrl("check-answers")

      Then("the user amends their trading name answers via check-answers")
      registration.selectChangeOrRemoveLink(
        "check-have-uk-trading-name"
      )
      registration.checkJourneyUrl("check-have-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-uk-trading-name/1")
      registration.enterAnswer("new trading name")
      registration.checkJourneyUrl("check-add-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-uk-trading-name/2")
      registration.enterAnswer("another company name")
      registration.checkJourneyUrl("check-add-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-answers")

      And("the user amends answers for eu tax details via check-answers")
      registration.selectChangeOrRemoveLink(
        "check-tax-in-eu"
      )
      registration.checkJourneyUrl("check-tax-in-eu")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-eu-tax/1")
      registration.selectCountry("Poland")
      registration.checkJourneyUrl("check-sells-goods-to-eu-consumers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-sells-goods-to-eu-consumer-method/1")
      registration.answerFixedEstablishment("fixed establishment")
      registration.checkJourneyUrl("check-registration-type/1")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("check-eu-vat-number/1")
      registration.enterAnswer("PL1234567890")
      registration.checkJourneyUrl("check-eu-trading-name/1")
      registration.enterAnswer("Poland Sales")
      registration.checkJourneyUrl("check-eu-fixed-establishment-address/1")
      registration.enterFixedEstablishmentAddress("1 Address", "", "A town", "", "")
      registration.checkJourneyUrl("change-check-tax-details/1")
      registration.continue()
      registration.checkJourneyUrl("check-add-tax-details")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-eu-tax/2")
      registration.selectCountry("Finland")
      registration.checkJourneyUrl("check-sells-goods-to-eu-consumers/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-sells-goods-to-eu-consumer-method/2")
      registration.answerFixedEstablishment("fixed establishment")
      registration.checkJourneyUrl("check-registration-type/2")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("check-eu-vat-number/2")
      registration.enterAnswer("FI12345678")
      registration.checkJourneyUrl("check-eu-trading-name/2")
      registration.enterAnswer("Finland Goods")
      registration.checkJourneyUrl("check-eu-fixed-establishment-address/2")
      registration.enterFixedEstablishmentAddress("1 Address", "", "A town", "", "SL123355")
      registration.checkJourneyUrl("change-check-tax-details/2")
      registration.continue()
      registration.checkJourneyUrl("check-add-tax-details")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-answers")

      And("the user amends answers for previous schemes via check-answers")
      registration.selectChangeOrRemoveLink(
        "check-previous-schemes-overview"
      )
      registration.checkJourneyUrl("check-previous-schemes-overview")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-previous-country/2")
      registration.selectCountry("Austria")
      registration.checkJourneyUrl("check-previous-scheme/2/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("check-previous-oss-scheme-number/2/1")
      registration.enterAnswer("ATU99999999")
      registration.checkJourneyUrl("check-previous-scheme-answers/2")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-previous-schemes-overview")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-start-date")
      registration.continue()
      registration.checkJourneyUrl("check-answers")

      And("the user amends their website address answers via check-answers")
      registration.selectChangeOrRemoveLink(
        "check-give-website-address"
      )
      registration.checkJourneyUrl("check-give-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-website-address/1")
      registration.enterAnswer("www.example.com")
      registration.checkJourneyUrl("check-add-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-website-address/2")
      registration.enterAnswer("www.second-example.com")
      registration.checkJourneyUrl("check-add-website-address")
      registration.selectChangeOrRemoveLink(
        "check-remove-website-address\\/2"
      )
      registration.checkJourneyUrl("check-remove-website-address/2")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-add-website-address")
      registration.answerRadioButton("no")

      And("the user submits the registration on the check-answers page")
      registration.checkJourneyUrl("check-answers")
      registration.submit()

      Then("the user is on the successful submission page")
      registration.checkJourneyUrl("successful")
    }

    Scenario("Changing answers from yes to no from CYA to show delete all pages") {

      Given("the user accesses the OSS Registration Service")
      auth.goToAuthorityWizard()
      auth.loginUsingAuthorityWizard("100000001", "Organisation", "vatOnly", "registration")
      registration.checkJourneyUrl("already-eu-registered")

      When("the user provides answers for their registration")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("sell-from-northern-ireland")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("northern-ireland-business")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("business-pay")
      registration.continue()
      registration.checkJourneyUrl("confirm-vat-details")
      registration.answerVatDetailsChoice("Yes")
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/1")
      registration.enterAnswer("Trading Name")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("uk-trading-name/2")
      registration.enterAnswer("Another One")
      registration.checkJourneyUrl("add-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("already-made-sales")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("date-of-first-sale")
      registration.enterDate("yesterday")
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-country/1")
      registration.selectCountry("Sweden")
      registration.checkJourneyUrl("previous-scheme/1/1")
      registration.answerSchemeType("OSS")
      registration.checkJourneyUrl("previous-oss-scheme-number/1/1")
      registration.enterAnswer("SE012345678987")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-scheme/1/2")
      registration.answerSchemeType("IOSS")
      registration.checkJourneyUrl("previous-ioss-scheme/1/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("previous-ioss-number/1/2")
      registration.enterIossNumber("IM7527777777")
      registration.checkJourneyUrl("previous-scheme-answers/1")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-schemes-overview")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("start-date")
      registration.continue()
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/1")
      registration.selectCountry("Croatia")
      registration.checkJourneyUrl("sells-goods-to-eu-consumers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("sells-goods-to-eu-consumer-method/1")
      registration.answerFixedEstablishment("fixed establishment")
      registration.checkJourneyUrl("registration-type/1")
      registration.selectRegistrationType("tax id number")
      registration.checkJourneyUrl("eu-tax-number/1")
      registration.enterAnswer("CR987654")
      registration.checkJourneyUrl("eu-trading-name/1")
      registration.enterAnswer("Croatian Products")
      registration.checkJourneyUrl("eu-fixed-establishment-address/1")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A town", "", "")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/2")
      registration.selectCountry("Finland")
      registration.checkJourneyUrl("sells-goods-to-eu-consumers/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("sells-goods-to-eu-consumer-method/2")
      registration.answerFixedEstablishment("dispatch warehouse")
      registration.checkJourneyUrl("registration-type/2")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("eu-vat-number/2")
      registration.enterAnswer("FI12345678")
      registration.checkJourneyUrl("eu-send-goods-trading-name/2")
      registration.enterAnswer("Finnish Sales")
      registration.checkJourneyUrl("eu-send-goods-address/2")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A town", "", "12345")
      registration.checkJourneyUrl("check-tax-details/2")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("online-marketplace")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("give-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("website-address/1")
      registration.enterAnswer("www.website1.co.uk")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("website-address/2")
      registration.enterAnswer("www.another-website.org")
      registration.checkJourneyUrl("add-website-address")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("business-contact-details")
      registration.fillContactDetails("Joe Bloggs", "01234567890", "email@test.com")
      email.completeEmailVerification("registration")
      registration.checkJourneyUrl("bank-details")
      registration.fillBankAccountDetails("Account Name", "SMCOGB2LXXM", "GB29NWBK60161331926819")
      registration.checkJourneyUrl("check-answers")

      Then("the user can remove all of their trading names")
      registration.selectChangeOrRemoveLink(
        "check-have-uk-trading-name"
      )
      registration.checkJourneyUrl("check-have-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-remove-all-trading-names")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-answers")

      Then("the user can remove all of their previous schemes")
      registration.selectChangeOrRemoveLink(
        "check-previous-oss"
      )
      registration.checkJourneyUrl("check-previous-oss")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-remove-all-previous-registrations")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-answers")

      Then("the user can remove all of their tax details")
      registration.selectChangeOrRemoveLink(
        "check-tax-in-eu"
      )
      registration.checkJourneyUrl("check-tax-in-eu")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-remove-all-eu-details")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-answers")

      Then("the user can remove all of their website addresses")
      registration.selectChangeOrRemoveLink(
        "check-give-website-address"
      )
      registration.checkJourneyUrl("check-give-website-address")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("check-remove-all-websites")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("check-answers")

      When("the user submits the registration on the check-answers page")
      registration.checkJourneyUrl("check-answers")
      registration.submit()

      Then("the user is on the successful submission page")
      registration.checkJourneyUrl("successful")
    }

    Scenario("Changing answers for EU registrations whilst progressing through the journey") {

      Given("the user accesses the OSS Registration Service")
      auth.goToAuthorityWizard()
      auth.loginUsingAuthorityWizard("100000001", "Organisation", "vatOnly", "registration")
      registration.checkJourneyUrl("already-eu-registered")

      When("the user provides answers for their registration up to the tax details section")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("sell-from-northern-ireland")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("northern-ireland-business")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("business-pay")
      registration.continue()
      registration.checkJourneyUrl("confirm-vat-details")
      registration.answerVatDetailsChoice("Yes")
      registration.checkJourneyUrl("have-uk-trading-name")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("already-made-sales")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("previous-oss")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("start-date")
      registration.continue()

      Then("the user adds tax details for a country")
      registration.checkJourneyUrl("tax-in-eu")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/1")
      registration.selectCountry("Netherlands")
      registration.checkJourneyUrl("sells-goods-to-eu-consumers/1")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("sells-goods-to-eu-consumer-method/1")
      registration.answerFixedEstablishment("dispatch warehouse")
      registration.checkJourneyUrl("registration-type/1")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("eu-vat-number/1")
      registration.enterAnswer("NL0123456789AB")
      registration.checkJourneyUrl("eu-send-goods-trading-name/1")
      registration.enterAnswer("Amsterdam Goods")
      registration.checkJourneyUrl("eu-send-goods-address/1")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A town", "", "")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.continue()

      Then("the user adds tax details for another country")
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("eu-tax/2")
      registration.selectCountry("Denmark")
      registration.checkJourneyUrl("sells-goods-to-eu-consumers/2")
      registration.answerRadioButton("yes")
      registration.checkJourneyUrl("sells-goods-to-eu-consumer-method/2")
      registration.answerFixedEstablishment("fixed establishment")
      registration.checkJourneyUrl("registration-type/2")
      registration.selectRegistrationType("tax id number")
      registration.checkJourneyUrl("eu-tax-number/2")
      registration.enterAnswer("D123456")
      registration.checkJourneyUrl("eu-trading-name/2")
      registration.enterAnswer("Danish Trading")
      registration.checkJourneyUrl("eu-fixed-establishment-address/2")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A town", "", "")
      registration.checkJourneyUrl("check-tax-details/2")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")

      Then("the user amends the tax details for the first country to use a tax id number")
      registration.selectChangeOrRemoveLink("check-tax-details\\/1")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.selectChangeOrRemoveLink("sells-goods-to-eu-consumer-method\\/1")
      registration.checkJourneyUrl("sells-goods-to-eu-consumer-method/1")
      registration.answerFixedEstablishment("fixed establishment")
      registration.checkJourneyUrl("registration-type/1")
      registration.selectRegistrationType("tax id number")
      registration.checkJourneyUrl("eu-tax-number/1")
      registration.enterAnswer("C9876")
      registration.checkJourneyUrl("eu-trading-name/1")
      registration.enterAnswer("A trading name")
      registration.checkJourneyUrl("eu-fixed-establishment-address/1")
      registration.enterFixedEstablishmentAddress("1 Street Name", "", "A town", "", "")
      registration.checkJourneyUrl("check-tax-details/1")

      And("the user amends the trading name for the first country")
      registration.selectChangeOrRemoveLink("first-check-eu-trading-name\\/1")
      registration.checkJourneyUrl("first-check-eu-trading-name/1")
      registration.enterAnswer("123")
      registration.checkJourneyUrl("check-tax-details/1")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")

      And("the user changes the tax details for the second country to use a vat number")
      registration.selectChangeOrRemoveLink("check-tax-details\\/2")
      registration.checkJourneyUrl("check-tax-details/2")
      registration.selectChangeOrRemoveLink("registration-type\\/2")
      registration.checkJourneyUrl("registration-type/2")
      registration.selectRegistrationType("vat number")
      registration.checkJourneyUrl("eu-vat-number/2")
      registration.enterAnswer("DK12345678")
      registration.checkJourneyUrl("eu-trading-name/2")
      registration.continue()
      registration.checkJourneyUrl("eu-fixed-establishment-address/2")
      registration.updateField("line2", "second line")
      registration.continue()
      registration.checkJourneyUrl("check-tax-details/2")
      registration.continue()
      registration.checkJourneyUrl("add-tax-details")
      registration.answerRadioButton("no")

      And("the user completes the rest of their registration")
      registration.checkJourneyUrl("online-marketplace")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("give-website-address")
      registration.answerRadioButton("no")
      registration.checkJourneyUrl("business-contact-details")
      registration.fillContactDetails("Joe Bloggs", "+01234567890", "email@test.com")
      email.completeEmailVerification("registration")
      registration.checkJourneyUrl("bank-details")
      registration.fillBankAccountDetails("Account Name", "", "GB33BUKB20201555555555")
      registration.checkJourneyUrl("check-answers")
      registration.submit()

      Then("the user is on the successful submission page")
      registration.checkJourneyUrl("successful")
    }
  }
}
